apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-deployment
  namespace: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: jupyter
        image: jupyter/pyspark-notebook:latest
        ports:
        - containerPort: 8888
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: notebook-storage
          mountPath: /home/jovyan/work
      volumes:
      - name: notebook-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
  namespace: jupyter
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30001
  selector:
    app: jupyter
