# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: airflow-logs-pv
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: standard
#   hostPath:
#     path: "/mnt/data/airflow-logs"

apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path : "/opt/airflow/logs"

# -----------------------------------------------------------------

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard