#============================================================================================
# componente: airbyte_deployer
# namespace: airbyte
# chart: airbyte
# release: airbyte
# version: 0.1.0
# criado em: 2024-08-29
#=============================================================================================
# Objetivo:
#   - Este componente é responsável por realizar o deploy do Airbyte em um cluster Kubernetes.
#=============================================================================================
# Recursos:
#   - 1 Deployment
#   - 1 Service
#   - 1 Ingress
#   - 1 PersistentVolume
#   - 1 PersistentVolumeClaim
#=============================================================================================
# Dependências:
#   - Nenhuma
#=============================================================================================
# Configurações:
#   - Nome do release: airbyte
#   - Namespace: airbyte
#   - Versão do Chart: 0.1.0
#   - Porta do serviço: 8000
#   - URL de acesso: airbyte.local
#   - Volume: 10Gi
#=============================================================================================
# Comandos:
#   - Instalação: helm install airbyte airbyte/airbyte -n airbyte -f airbyte_deployer.yaml
#   - Atualização: helm upgrade airbyte airbyte/airbyte -n airbyte -f airbyte_deployer.yaml
#   - Desinstalação: helm uninstall airbyte -n airbyte
#=============================================================================================
# Notas:
#   - Nenhuma
#=============================================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte
  namespace: airbyte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airbyte
  template:
    metadata:
      labels:
        app: airbyte
    spec:
      containers:
      - name: airbyte
        image: airbyte/airbyte:latest
        ports:
        - containerPort: 8000
        env:
        - name: AIRBYTE_PORT
          value: "8000"
        volumeMounts:
        - name: airbyte-storage
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: airbyte-service
  namespace: airbyte
spec:
  selector:
    app: airbyte
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airbyte-ingress
  namespace: airbyte
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: airbyte.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: airbyte-service
            port:
              number: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airbyte-pv
  namespace: airbyte
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data/airbyte
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airbyte-pvc
  namespace: airbyte
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
---
apiVersion: v1
kind: Namespace
metadata:
  name: airbyte
